openapi: 3.0.0
servers: 
  - url: 'https://organizador-restapi.ew.r.appspot.com'
info:
  description: Organízate fácilmente con API Organizador
  version: 1.0.0
  title: API Organizador
  contact:
    email: enrmunper@alum.us.es
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: tarea
    description: tarea
  - name: listas
    description: listas
paths:
  /tarea:
    get:
      tags:
        - tarea
      summary: Get tarea
      description: Get all tarea
      operationId: gettarea
      parameters:
        - name: order
          in: query
          description: Order results by titulo or fechaVencimiento
          required: false
          schema:
            type: string
            enum:
              - titulo
              - '-titulo'
              - fechaVencimiento
              - '-fechaVencimiento'
        - name: progreso
          in: query
          description: Order results by progreso
          required: false
          schema:
            type: string
            enum:
              - SIN_COMENZAR
              - EN_PROGRESO
              - TERMINADO
        - name: prioridad
          in: query
          description: Order results by prioridad
          required: false
          schema:
            type: string
            enum:
              - BAJA
              - MEDIA
              - ALTA
        - name: q
          in: query
          description: Query to filter
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description:  Maximum number of results
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
        - name: offset
          in: query
          description: Offset of the results
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '200':
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tarea'
        '400':
          description: Bad request
    post:
      tags:
        - tarea
      summary: Create a tarea
      description: Create a tarea
      operationId: createtarea
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - titulo
              properties:
                id:
                  type: string
                titulo:
                  type: string
                descripcion:
                  type: string
                categoria:
                  type: string
                completado:
                  type: string
                ubicacion:
                  type: string
              example:
                  id: 't01'
                  titulo: Hacer parte de integración proyecto AISS
                  descripcion: Buscar proyecto para integrar
                  categoria: Universidad
                  completado: true
                  prioridad: ALTA
                  progreso: EN_PROGRESO
                  fechaVencimiento: '2021-05-17'
                  ubicacion: ETSII
        description: tarea to create
        required: true
      responses:
        '201':
          description: tarea created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tarea'
        '400':
          description: Bad request
    put:
      tags:
        - tarea
      summary: Update a tarea
      description: Change a tarea
      operationId: changetarea
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - titulo
              properties:
                id:
                  type: string
                titulo:
                  type: string
                descripcion:
                  type: string
                categoria:
                  type: string
                completado:
                  type: string
              example:
                  id: 't01'
                  titulo: Hacer parte de integración proyecto AISS
                  descripcion: Buscar proyecto para integrar
                  categoria: Universidad
                  completado: true
                  prioridad: ALTA
                  progreso: EN_PROGRESO
                  fechaVencimiento: '2021-05-17'
                  ubicacion: ETSII
        description: tarea to update
        required: true
      responses:
        '201':
          description: tarea created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tarea'
        '400':
          description: Bad request
  '/tarea/{id}':
    get:
      tags:
        - tarea
      summary: Get id tarea
      description: Get id tarea
      operationId: gettareaId
      parameters:
        - name: id
          in: path
          description: Id of the tarea
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tarea'
        '400':
          description: Bad request
    delete:
      tags:
        - tarea
      summary: Delete tarea
      description: Delete tarea
      operationId: deletetarea
      parameters:
        - name: id
          in: path
          description: Id of the tarea
          required: true
          schema:
            type: string
      responses:
        '204':
          description: tarea deleted
        '404':
          description: tarea not found
  /listas:
    get:
      tags:
        - listas
      summary: Get listas
      description: Get all listas
      operationId: getlistas
      parameters:
        - name: order
          in: query
          description: Order results by titulo
          required: false
          schema:
            type: string
            enum:
              - titulo
              - '-titulo'
        - name: isEmpty
          in: query
          description: Filter listas with no tarea
          required: false
          schema:
            type: boolean
        - name: name
          in: query
          description: Filter listas by name
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/lista'
        - name: limit
          in: query
          description:  Maximum number of results
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
        - name: offset
          in: query
          description: Offset of the results
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0      
        
      responses:
        '200':
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/lista'
        '400':
          description: Bad request
    post:
      tags:
        - listas
      summary: Create a list
      description: Create a list
      operationId: createList
      requestBody:
        content:
          application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/lista'
        description: lista to create
      responses:
        '204':
          description: lista created
        '400':
          description: Bad request
    put:
      tags:
        - listas
      summary: Update a lista
      description: Update a lista
      operationId: updatelista
      requestBody:
        content:
          application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/lista'
        description: lista to update
      responses:
        '204':
          description: lista updated
        '400':
          description: Bad request
        '404':
          description: lista not found
  '/listas/{id}':
    get:
      tags:
        - listas
      summary: Get a lista
      description: Get a lista
      operationId: getlista
      parameters:
        - name: id
          in: path
          description: Id of the lista
          required: true
          schema:
            type: string
      responses:
        '200':
          description: lista found
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/lista'
        '404':
          description: lista not found
    delete:
      tags:
        - listas
      summary: Delete List
      description: Delete List
      operationId: deleteList
      parameters:
        - name: id
          in: path
          description: Id of the list
          required: true
          schema:
            type: string
      responses:
        '204':
          description: List deleted
        '404':
          description: List not found
  '/listas/{listaId}/{tareaId}':
    post:
      tags:
        - listas
      summary: Add tarea to lista
      description: Add tarea to lista
      operationId: addtareaTolista
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      parameters:
        - name: listaId
          in: path
          description: Id of the lista
          required: true
          schema:
            type: string
        - name: tareaId
          in: path
          description: Id of the tarea
          required: true
          schema:
            type: string
      responses:
        '201':
          description: tarea added to lista
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/lista'
        '400':
          description: Bad request
        '404':
          description: lista or tarea not found
    delete:
      tags:
        - listas
      summary: Delete tarea from lista
      description: Delete tarea from lista
      operationId: deletetareaFromPlayist
      parameters:
        - name: listaId
          in: path
          description: Id of the lista
          required: true
          schema:
            type: string
        - name: tareaId
          in: path
          description: Id of the tarea
          required: true
          schema:
            type: string
      responses:
        '204':
          description: tarea deleted from lista
        '404':
          description: lista or tarea not found
components:
  schemas:
    tarea:
      required: 
        - titulo
      properties:
        id:
          type: string
        titulo:
          type: string
        descripcion:
          type: string
        categoria:
          type: string
        completado:
          type: boolean
        prioridad:
          type: string
        progreso:
          type: string
        fechaVencimiento:
          type: string
        ubicacion:
          type: string
      example:
          id: 't01'
          titulo: Hacer parte de integración proyecto AISS
          descripcion: Buscar proyecto para integrar
          categoria: Universidad
          completado: true
          prioridad: ALTA
          progreso: EN_PROGRESO
          fechaVencimiento: '2021-05-17'
          ubicacion: ETSII
    lista:
      required: 
        - titulo
      properties:
        id:
          type: string
        titulo:
          type: string
        descripcion:
          type: string
        tarea:
          type: array
          items: 
            $ref: '#/components/schemas/tarea'
      example:
        id: 'l01'
        titulo: Proyectos universidad
        description: Proyectos de las asignaturas de la universidad
        tarea:
             - id: 't01'
               titulo: Hacer parte de integración proyecto AISS
               descripcion: Buscar proyecto para integrar
               categoria: Universidad
               completado: true
               prioridad: ALTA
               progreso: EN_PROGRESO
               fechaVencimiento: '2021-05-17'
               ubicacion: ETSII